import { SegmentIF, MeetingIF } from '@/interfaces';
import { getNextWednesday } from '@/utils/utils';

const DEFAULT_SEGMENTS_REGULAR_MEETING: SegmentIF[] = [
  {
    segment_id: '1',
    segment_type: 'Members and Guests Registration, Warm up',
    start_time: '19:15',
    duration: '15',
    end_time: '19:30',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '2',
    segment_type: 'Meeting Rules Introduction (SAA)',
    start_time: '19:30',
    duration: '3',
    end_time: '19:33',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '3',
    segment_type: 'Opening Remarks (President)',
    start_time: '19:33',
    duration: '2',
    end_time: '19:35',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '4',
    segment_type: 'TOM (Toastmaster of Meeting) Introduction',
    start_time: '19:35',
    duration: '2',
    end_time: '19:37',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '5',
    segment_type: 'Timer',
    start_time: '19:37',
    duration: '3',
    end_time: '19:40',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '6',
    segment_type: 'Hark Master',
    start_time: '19:40',
    duration: '3',
    end_time: '19:43',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '7',
    segment_type: 'Guests Self Introduction (30s per guest)',
    start_time: '19:43',
    duration: '8',
    end_time: '19:51',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '8',
    segment_type: 'TTM (Table Topic Master) Opening',
    start_time: '19:52',
    duration: '4',
    end_time: '19:56',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '9',
    segment_type: 'Table Topic Session',
    start_time: '19:56',
    duration: '16',
    end_time: '20:12',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '10',
    segment_type: 'Prepared Speech 1',
    start_time: '20:13',
    duration: '7',
    end_time: '20:20',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '11',
    segment_type: 'Prepared Speech 2',
    start_time: '20:21',
    duration: '7',
    end_time: '20:28',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '12',
    segment_type: 'Tea Break & Group Photos',
    start_time: '20:29',
    duration: '12',
    end_time: '20:41',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '13',
    segment_type: 'Table Topic Evaluation',
    start_time: '20:42',
    duration: '7',
    end_time: '20:49',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '14',
    segment_type: 'Prepared Speech 1 Evaluation',
    start_time: '20:50',
    duration: '3',
    end_time: '20:53',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '10',
  },
  {
    segment_id: '15',
    segment_type: 'Prepared Speech 2 Evaluation',
    start_time: '20:54',
    duration: '3',
    end_time: '20:57',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '11',
  },
  {
    segment_id: '16',
    segment_type: "Timer's Report",
    start_time: '20:58',
    duration: '2',
    end_time: '21:00',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '17',
    segment_type: 'General Evaluation',
    start_time: '21:01',
    duration: '4',
    end_time: '21:05',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '18',
    segment_type: 'Voting Section (TOM)',
    start_time: '21:06',
    duration: '2',
    end_time: '21:08',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '19',
    segment_type: 'Awards/President',
    start_time: '21:09',
    duration: '3',
    end_time: '21:12',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
  {
    segment_id: '20',
    segment_type: 'Closing Remarks/President',
    start_time: '21:13',
    duration: '2',
    end_time: '21:15',
    role_taker: '',
    title: '',
    content: '',
    related_segment_ids: '',
  },
];

export const DEFAULT_REGULAR_MEETING: MeetingIF = {
  meeting_type: 'Regular',
  theme: '',
  meeting_manager: '',
  date: getNextWednesday().date,
  start_time: '19:15',
  end_time: '21:30',
  location:
    "JOININ HUB, 6th Xin'an Rd, Bao'an (Metro line 1 Baoti / line 11 Bao'an)",
  introduction: '',
  segments: DEFAULT_SEGMENTS_REGULAR_MEETING,
};
