repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
        entry: bash -c 'cd backend && ruff check .'
      - id: ruff-format
        files: ^backend/
        entry: bash -c 'cd backend && ruff format .'

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        files: ^backend/
        entry: bash -c 'cd backend && mypy .'
        language: system
        types: [python]
        require_serial: true
        verbose: true
