export const meetings = [
  {
    meeting_type: 'Regular',
    theme: 'Aging',
    meeting_manager: 'Rui Zheng',
    date: 'Nov. 6, 2024 (Wed)',
    start_time: '19:15',
    end_time: '21:30',
    location:
      "JOININ HUB, 6th Xin'an Rd, Bao'an (Metro line 1 Baoti / line 11 Bao'an)",
    introduction:
      "Join us for an engaging Toastmasters session where we'll explore various aspects of public speaking. This meeting promises to be an enriching experience with prepared speeches, impromptu speaking sessions, and constructive evaluations. Whether you're a seasoned speaker or just starting out, you'll find valuable opportunities to grow.",
    segments: [
      {
        segment_id: '1',
        segment_type: 'Members and Guests Registration, Warm up',
        start_time: '19:15',
        duration: '15',
        end_time: '19:30',
        role_taker: 'All',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '2',
        segment_type: 'Meeting Rules Introduction (SAA)',
        start_time: '19:30',
        duration: '3',
        end_time: '19:33',
        role_taker: 'Joyce',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '3',
        segment_type: 'Opening Remarks (President)',
        start_time: '19:33',
        duration: '2',
        end_time: '19:35',
        role_taker: 'Frank',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '4',
        segment_type: 'TOM (Toastmaster of Meeting) Introduction',
        start_time: '19:35',
        duration: '2',
        end_time: '19:37',
        role_taker: 'Rui',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '5',
        segment_type: 'Timer',
        start_time: '19:37',
        duration: '3',
        end_time: '19:40',
        role_taker: 'Max',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '6',
        segment_type: 'Hark Master',
        start_time: '19:40',
        duration: '3',
        end_time: '19:43',
        role_taker: 'Mia',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '7',
        segment_type: 'Guests Self Introduction (30s per guest)',
        start_time: '19:43',
        duration: '8',
        end_time: '19:51',
        role_taker: 'Joseph',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '8',
        segment_type: 'TTM (Table Topic Master) Opening',
        start_time: '19:52',
        duration: '4',
        end_time: '19:56',
        role_taker: 'Rui',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '9',
        segment_type: 'Table Topic Session',
        start_time: '19:56',
        duration: '16',
        end_time: '20:12',
        role_taker: 'All',
        title: '',
        content: 'WOT (Word of Today): Immortal',
        related_segment_ids: '',
      },
      {
        segment_id: '10',
        segment_type: 'Prepared Speech 1',
        start_time: '20:13',
        duration: '7',
        end_time: '20:20',
        role_taker: 'Frank',
        title: 'Failures are learned experiences',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '11',
        segment_type: 'Prepared Speech 2',
        start_time: '20:21',
        duration: '7',
        end_time: '20:28',
        role_taker: 'Libra',
        title: 'Do you fear aging?',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '12',
        segment_type: 'Tea Break & Group Photos',
        start_time: '20:29',
        duration: '12',
        end_time: '20:41',
        role_taker: 'All',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '13',
        segment_type: 'Table Topic Evaluation',
        start_time: '20:42',
        duration: '7',
        end_time: '20:49',
        role_taker: 'Emily',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '14',
        segment_type: 'Prepared Speech 1 Evaluation',
        start_time: '20:50',
        duration: '3',
        end_time: '20:53',
        role_taker: 'Phyllis',
        title: '',
        content: '',
        related_segment_ids: '10',
      },
      {
        segment_id: '15',
        segment_type: 'Prepared Speech 2 Evaluation',
        start_time: '20:54',
        duration: '3',
        end_time: '20:57',
        role_taker: 'Amanda',
        title: '',
        content: '',
        related_segment_ids: '11',
      },
      {
        segment_id: '16',
        segment_type: "Timer's Report",
        start_time: '20:58',
        duration: '2',
        end_time: '21:00',
        role_taker: 'Max',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '17',
        segment_type: 'Hark Master Pop Quiz Time',
        start_time: '21:01',
        duration: '5',
        end_time: '21:06',
        role_taker: 'Mia',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '18',
        segment_type: 'General Evaluation',
        start_time: '21:07',
        duration: '4',
        end_time: '21:11',
        role_taker: 'Karman',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '19',
        segment_type: 'Voting Section (TOM)',
        start_time: '21:16',
        duration: '2',
        end_time: '21:18',
        role_taker: 'Rui',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '20',
        segment_type: 'Moment of Truth',
        start_time: '21:19',
        duration: '7',
        end_time: '21:26',
        role_taker: 'Leta',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '21',
        segment_type: 'Awards/President',
        start_time: '21:27',
        duration: '3',
        end_time: '21:30',
        role_taker: 'Frank',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '22',
        segment_type: 'Closing Remarks/President',
        start_time: '21:30',
        duration: '1',
        end_time: '21:31',
        role_taker: 'Frank',
        title: '',
        content: '',
        related_segment_ids: '',
      },
    ],
  },
  {
    meeting_type: 'Regular',
    theme: 'Review 2024, Envision 2025',
    meeting_manager: 'Joseph',
    date: 'Jan. 15 2025 (Wed)',
    start_time: '19:15',
    end_time: '21:30',
    location:
      "JOININ HUB, 6th Xin'an Rd,Bao'an (Metro line 1 Baoti / line 11 Bao'an)",
    introduction:
      "Join us for an engaging Toastmasters session where we'll explore various aspects of public speaking. This meeting promises to be an enriching experience with prepared speeches, impromptu speaking sessions, and constructive evaluations. Whether you're a seasoned speaker or just starting out, you'll find valuable opportunities to grow.",
    segments: [
      {
        segment_id: '1',
        segment_type: 'Members and Guests Registration, Warm up',
        start_time: '19:15',
        duration: '15',
        end_time: '19:30',
        role_taker: 'All',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '2',
        segment_type: 'Meeting Rules Introduction (SAA)',
        start_time: '19:30',
        duration: '2',
        end_time: '19:32',
        role_taker: 'Joyce',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '3',
        segment_type: 'Opening Remarks (President)',
        start_time: '19:32',
        duration: '2',
        end_time: '19:34',
        role_taker: 'Libra',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '4',
        segment_type: 'TOM (Toastmaster of Meeting) Introduction',
        start_time: '19:34',
        duration: '2',
        end_time: '19:36',
        role_taker: 'Jessica',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '5',
        segment_type: 'Timer',
        start_time: '19:36',
        duration: '2',
        end_time: '19:38',
        role_taker: 'Shelly (Guest)',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '6',
        segment_type: 'Guests Self Introduction (30s per guest)',
        start_time: '19:38',
        duration: '5',
        end_time: '19:43',
        role_taker: 'Helena (Guest)',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '7',
        segment_type: 'TTM (Table Topic Master) Opening',
        start_time: '19:44',
        duration: '2',
        end_time: '19:46',
        role_taker: 'Joseph',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '8',
        segment_type: 'Table Topic Session',
        start_time: '19:47',
        duration: '20',
        end_time: '20:07',
        role_taker: 'All',
        title: '',
        content: 'WOT (Word of Today): Goal',
        related_segment_ids: '',
      },
      {
        segment_id: '9',
        segment_type: 'Prepared Speech 1',
        start_time: '20:08',
        duration: '7',
        end_time: '20:15',
        role_taker: 'Frank',
        title: 'How to deal with conflicts',
        content:
          'The purpose of this project is to practice writing and delivering a speech that inspires others.',
        related_segment_ids: '',
      },
      {
        segment_id: '10',
        segment_type: 'Prepared Speech 2',
        start_time: '20:16',
        duration: '7',
        end_time: '20:23',
        role_taker: 'Joseph',
        title: 'Introduction of my company',
        content:
          'The purpose of this speech is for the member to present a speech and receive feedback from the evaluator.',
        related_segment_ids: '',
      },
      {
        segment_id: '11',
        segment_type: 'Prepared Speech 3',
        start_time: '20:24',
        duration: '7',
        end_time: '20:31',
        role_taker: 'Snow',
        title: 'My review on 2024 and envision at 2025',
        content:
          'The purpose of this project is to learn or review basic methods for writing a speech with a defined purpose and to present a well-organized speech on any topic.',
        related_segment_ids: '',
      },
      {
        segment_id: '12',
        segment_type: 'Tea Break & Group Photos',
        start_time: '20:32',
        duration: '10',
        end_time: '20:42',
        role_taker: 'All',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '13',
        segment_type: 'Table Topic Evaluation',
        start_time: '20:43',
        duration: '7',
        end_time: '20:50',
        role_taker: 'Rui',
        title: '',
        content: '',
        related_segment_ids: '8',
      },
      {
        segment_id: '14',
        segment_type: 'Prepared Speech Evaluation 1',
        start_time: '20:51',
        duration: '3',
        end_time: '20:54',
        role_taker: 'Libra',
        title: '',
        content: '',
        related_segment_ids: '9',
      },
      {
        segment_id: '15',
        segment_type: 'Prepared Speech Evaluation 2',
        start_time: '20:55',
        duration: '3',
        end_time: '20:58',
        role_taker: 'Max',
        title: '',
        content: '',
        related_segment_ids: '10',
      },
      {
        segment_id: '16',
        segment_type: 'Prepared Speech Evaluation 3',
        start_time: '20:59',
        duration: '3',
        end_time: '21:02',
        role_taker: 'Amy',
        title: '',
        content: '',
        related_segment_ids: '11',
      },
      {
        segment_id: '17',
        segment_type: 'Timer’s Report',
        start_time: '21:03',
        duration: '2',
        end_time: '21:05',
        role_taker: 'Shelly (Guest)',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '18',
        segment_type: 'General Evaluation',
        start_time: '21:06',
        duration: '8',
        end_time: '21:14',
        role_taker: 'Diane (Foreseas)',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '19',
        segment_type: 'Voting Section (TOM)',
        start_time: '21:15',
        duration: '2',
        end_time: '21:17',
        role_taker: 'Jessica',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '20',
        segment_type: 'Moment of Truth',
        start_time: '21:17',
        duration: '8',
        end_time: '21:25',
        role_taker: 'Joyce',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '21',
        segment_type: 'Awards (President)',
        start_time: '21:26',
        duration: '3',
        end_time: '21:29',
        role_taker: 'Libra',
        title: '',
        content: '',
        related_segment_ids: '',
      },
      {
        segment_id: '22',
        segment_type: 'Closing Remarks (President)',
        start_time: '21:30',
        duration: '1',
        end_time: '21:31',
        role_taker: 'Libra',
        title: '',
        content: '',
        related_segment_ids: '',
      },
    ],
  },
];
