#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd -P)"
COMPOSE_FILE="${SCRIPT_DIR}/compose.yaml"
ENV_FILE="${SCRIPT_DIR}/.env.local"

usage() {
  printf 'Usage: %s {up|down|restart|shell|logs}\n' "${0##*/}" >&2
}

fail() {
  printf '%s\n' "$1" >&2
  exit 1
}

prompt() {
  local label="$1"
  local default_value="$2"
  local input

  if ! IFS= read -r -p "${label} [${default_value}]: " input; then
    fail "Setup cancelled."
  fi
  PROMPT_VALUE="${input:-${default_value}}"
}

prompt_secret() {
  local label="$1"
  local input

  if ! IFS= read -r -s -p "${label}: " input; then
    fail "Setup cancelled."
  fi
  printf '\n'
  PROMPT_VALUE="${input}"
}

expand_home() {
  case "$1" in
    "~")
      printf '%s\n' "${HOME}"
      ;;
    "~/"*)
      printf '%s/%s\n' "${HOME}" "${1#\~/}"
      ;;
    *)
      printf '%s\n' "$1"
      ;;
  esac
}

trim_trailing_slashes() {
  local value="$1"

  while [[ "${value}" != "/" && "${value}" == */ ]]; do
    value="${value%/}"
  done
  printf '%s\n' "${value}"
}

validate_mount_path() {
  local value="$1"
  local label="$2"

  [[ "${value}" == /* ]] ||
    fail "${label} must be an absolute path."

  case "${value}" in
    *"/../"*|*"/.."|*"/./"*|*"/.")
      fail "${label} must not contain . or .. path components."
      ;;
  esac

  [[ "${value}" != "/" && "${value}" != "${HOME}" ]] ||
    fail "${label} cannot be the filesystem root or complete home directory."

  case "${value}" in
    "${REPO_ROOT}"|"${REPO_ROOT}"/*)
      fail "${label} must be outside the SoarHigh repository."
      ;;
  esac
}

validate_separate_mounts() {
  local hermes_home="$1"
  local workspace="$2"

  case "${workspace}" in
    "${hermes_home}"|"${hermes_home}"/*)
      fail "Hermes workspace must not be inside Hermes home."
      ;;
  esac

  case "${hermes_home}" in
    "${workspace}"/*)
      fail "Hermes home must not be inside Hermes workspace."
      ;;
  esac
}

dotenv_quote() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$/\$\$}"
  printf '"%s"' "${value}"
}

configure_first_run() {
  local hermes_home
  local workspace
  local image
  local container_name
  local wxpost_service_token
  local confirmation
  local temp_file

  [[ -t 0 && -t 1 ]] ||
    fail "Missing ${ENV_FILE}; interactive setup requires a terminal."

  printf 'First-time Hermes container setup\n\n'

  prompt "Hermes home" "${HOME}/.hermes"
  hermes_home="$(trim_trailing_slashes "$(expand_home "${PROMPT_VALUE}")")"
  validate_mount_path "${hermes_home}" "Hermes home"
  [[ -d "${hermes_home}" ]] ||
    fail "Hermes home does not exist: ${hermes_home}"
  hermes_home="$(cd -- "${hermes_home}" && pwd -P)"
  validate_mount_path "${hermes_home}" "Hermes home"

  prompt "Hermes workspace" "${HOME}/hermes-workspace"
  workspace="$(trim_trailing_slashes "$(expand_home "${PROMPT_VALUE}")")"
  validate_mount_path "${workspace}" "Hermes workspace"
  validate_separate_mounts "${hermes_home}" "${workspace}"

  prompt "Hermes image" "nousresearch/hermes-agent:latest"
  image="${PROMPT_VALUE}"
  [[ -n "${image}" ]] || fail "Hermes image cannot be empty."

  prompt "Container name" "soarhigh-hermes"
  container_name="${PROMPT_VALUE}"
  [[ "${container_name}" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] ||
    fail "Container name may contain letters, numbers, _, ., and -."

  prompt_secret "Existing backend WXPOST service token"
  wxpost_service_token="${PROMPT_VALUE}"
  [[ -n "${wxpost_service_token}" ]] ||
    fail "WxPost service token must not be empty."

  printf '\nConfiguration:\n'
  printf '  Hermes home:      %s\n' "${hermes_home}"
  printf '  Hermes workspace: %s\n' "${workspace}"
  printf '  Hermes image:     %s\n' "${image}"
  printf '  Container name:   %s\n\n' "${container_name}"

  prompt "Write .env.local and start Hermes?" "y"
  confirmation="${PROMPT_VALUE}"
  case "${confirmation}" in
    y|Y|yes|YES)
      ;;
    *)
      fail "Setup cancelled; no configuration was written."
      ;;
  esac

  mkdir -p -- "${workspace}"
  workspace="$(cd -- "${workspace}" && pwd -P)"
  validate_mount_path "${workspace}" "Hermes workspace"
  validate_separate_mounts "${hermes_home}" "${workspace}"

  [[ ! -e "${ENV_FILE}" ]] ||
    fail "${ENV_FILE} appeared during setup; refusing to overwrite it."

  temp_file="$(mktemp "${SCRIPT_DIR}/.env.local.tmp.XXXXXX")"
  chmod 600 "${temp_file}"
  {
    printf '# Generated by hermes.sh on first startup.\n'
    printf 'HERMES_HOME_DIR=%s\n' "$(dotenv_quote "${hermes_home}")"
    printf 'HERMES_WORKSPACE_DIR=%s\n' "$(dotenv_quote "${workspace}")"
    printf 'HERMES_IMAGE=%s\n' "$(dotenv_quote "${image}")"
    printf 'HERMES_CONTAINER_NAME=%s\n' \
      "$(dotenv_quote "${container_name}")"
    printf 'SOARHIGH_WXPOST_SERVICE_TOKEN=%s\n' \
      "$(dotenv_quote "${wxpost_service_token}")"
  } >"${temp_file}"
  mv -- "${temp_file}" "${ENV_FILE}"

  printf 'Wrote %s\n\n' "${ENV_FILE}"
}

[[ $# -eq 1 ]] || {
  usage
  exit 2
}

case "$1" in
  up|down|restart|shell|logs)
    action="$1"
    ;;
  *)
    usage
    exit 2
    ;;
esac

[[ ! -e "${ENV_FILE}" || -f "${ENV_FILE}" ]] ||
  fail "${ENV_FILE} exists but is not a regular file."

if [[ ! -f "${ENV_FILE}" ]]; then
  if [[ "${action}" == "up" ]]; then
    configure_first_run
  else
    fail "Missing ${ENV_FILE}; run hermes.sh up once to configure it."
  fi
fi

command -v docker >/dev/null 2>&1 ||
  fail "Docker CLI is not installed or is not on PATH."
docker compose version >/dev/null 2>&1 ||
  fail "Docker Compose v2 is not available."

export HERMES_UID="${HERMES_UID:-$(id -u)}"
export HERMES_GID="${HERMES_GID:-$(id -g)}"

compose() {
  docker compose \
    --env-file "${ENV_FILE}" \
    --file "${COMPOSE_FILE}" \
    "$@"
}

compose config --quiet

case "${action}" in
  up)
    compose up --detach
    ;;
  down)
    compose down
    ;;
  restart)
    # The controller joins the gateway's network namespace. Restarting both
    # containers in parallel can leave it trying to join a gateway that is
    # temporarily stopped, so bring them back in dependency order.
    compose stop controller gateway
    compose up --detach gateway
    compose up --detach controller
    ;;
  shell)
    compose exec \
      --user hermes \
      --workdir /workspace \
      --env HOME=/opt/data \
      gateway \
      bash
    ;;
  logs)
    compose logs --tail 100 --follow gateway
    ;;
esac
